num1=int(input("Enter the number 1 : "))
num2=int(input("Enter the number 2 : "))
num3=int(input("Enter the number 3 : "))
maximum=max(num1,num2,num3)
print(f"The Maximum number is the : {maximum}")